### ISSUE TITLE
Some Shaders Don't Work

### ISSUE THREAD

**Issue by msj121** [msj121/aframeFrogShaders#1]
The following shader doesn't work:

Enter_The_Matrix.json

```
Uncaught TypeError: Cannot read property 'x' of undefined(…)
s	@	three.js:31441
THREE.WebGLUniforms.U.upload	@	three.js:31820
b	@	three.js:26727
renderBufferDirect	@	three.js:25522
y	@	three.js:26289
render	@	three.js:26042
render	@	VREffect.js:376
value	@	a-scene.js:424
(anonymous function)	@	bind.js:12
```

https://rawgit.com/msj121/aframeFrogShaders/master/examples/error.html

**Comment by donmccurdy** [comment]
FWIW, I've gotten this exact error when using a custom shader (e.g. `AFRAME.registerShader(...)`) because of doing something like:

```
{
  uniforms: {
    foo: new THREE.Vector3()
  }
}
```

instead of:

```
{
  uniforms: {
    foo: {value: new THREE.Vector3()}
  }
}
```

So I would guess that a uniform is being set incorrectly somewhere in the shaderfrog->threejs conversion.

**Comment by msj121** [comment]
Oh wow! Thanks for the heads up! This will hopefully narrow down my search for the code issue.
