### ISSUE TITLE
Broken with A-Frame 0.4.0

### ISSUE THREAD

**Issue by HulloImJay** [msj121/aframeFrogShaders#2]
Steps to Reproduce:
1) Change the provided example to use A-Frame 0.4.0:
`    <script src="https://aframe.io/releases/0.4.0/aframe.min.js"></script>`

2) Object renders as white. Observe the following error in the console.
```
Uncaught (in promise) TypeError: Cannot read property 'XHRLoader' of undefined
    at o (https://rawgit.com/msj121/aframeFrogShaders/master/aframe-shader-frog.js:1:1298)
```

**Comment by msj121** [comment]
The code js now working. Sadly requires a much bigger file now, but my local version is working.
